[global]

# If false, makes your Streamlit script wider, and the sidebar collapses to a small arrow.
wideMode = true

# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
dataFrameSerialization = "legacy"

[logger]

# Level of logging: 'error', 'warning', 'info', 'debug'.
level = "info"

[client]

# Whether to enable st.cache.
caching = true

# If false, will attempt to open a new tab or window every time Streamlit is
# called. If true, will only open a new tab the first time Streamlit is called.
showSidebarNavigation = true

[server]

# List of folders that should not be watched for changes. This impacts both
# "Run on Save" and @st.cache.
folderWatchBlacklist = ['']

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas,
# this should be set to the same value across all replicas to ensure they all
# share the same secret.
cookieSecret = "a-random-key-appears-here"

# If false, will attempt to open a new browser tab on the local development
# machine when `streamlit run` is called.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = false

# The address where the server will listen for client and browser connections.
address = "localhost"

# The port where the server will listen for client and browser connections.
port = 8501

[browser]

# Internet address where users should point their browsers in order to connect to
# the app. Can be IP address or DNS name and path.
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

# Port where users should point their browsers in order to connect to the app.
serverPort = 8501
